"""posts table



Revision ID: 6625b3bf9579
Revises: 78ccfcb838f3
Create Date: 2021-03-10 16:57:07.020180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6625b3bf9579'
down_revision = '78ccfcb838f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('attribute', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_attribute'), 'post', ['attribute'], unique=False)
    op.create_index(op.f('ix_post_category'), 'post', ['category'], unique=False)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_category'), table_name='post')
    op.drop_index(op.f('ix_post_attribute'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
